set vTableName 		= 'DIM_AERONAVE';
set vFileNameOrigin = 'aeronave(1).csv';
set vFileNameOutput = 'DIM_AERONAVE.QVD';

$(vTableName):
LOAD
    codigo_ocorrencia2,
    aeronave_matricula,
    aeronave_operador_categoria,
    aeronave_tipo_veiculo,

    aeronave_nivel_dano,
    aeronave_fatalidades_total
FROM [$(vPathImport)$(vFileNameOrigin)]
(txt, utf8, embedded labels, delimiter is ';', msq);

STORE $(vTableName) INTO [$(vPathExtract)$(vFileNameOutput)](qvd);

DROP TABLE $(vTableName);
